language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run